import { expect, it } from 'vitest'
import { createDomainDesigner } from '..'

it('字符串转换模板函数', () => {
  const d = createDomainDesigner()
  const desc = d.desc('default')
  const agg = d.agg('agg', {}, '')
  const event = agg.event('event', {}, '')
  const policy = event.policy('policy', '')
  const person = d.person('person', '')
  const system = d.system('system', '')
  const service = d.service('service', '')
  const field = d.field.id('field', '')
  const command = d.command('command', {}, '')
  const facadeCmd = d.facadeCmd('facadeCmd', {}, '')
  expect(desc._attributes.template.reduce).instanceOf(Function)
  expect(agg._attributes.description?._attributes.template.reduce).instanceOf(Function)
  expect(event._attributes.description?._attributes.template.reduce).instanceOf(Function)
  expect(policy._attributes.description?._attributes.template.reduce).instanceOf(Function)
  expect(person._attributes.description?._attributes.template.reduce).instanceOf(Function)
  expect(system._attributes.description?._attributes.template.reduce).instanceOf(Function)
  expect(service._attributes.description?._attributes.template.reduce).instanceOf(Function)
  expect(field._attributes.description?._attributes.template.reduce).instanceOf(Function)
  expect(command._attributes.description?._attributes.template.reduce).instanceOf(Function)
  expect(facadeCmd._attributes.description?._attributes.template.reduce).instanceOf(Function)
})
